apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      # Türetilen label'ları otomatik filtre olarak göster
      derivedFields:
        - name: correlation_id
          matcherRegex: '"correlation_id":"([^"]+)"'
          url: ""
          datasourceUid: ""
        - name: tx_hash
          matcherRegex: '"tx_hash":"(0x[0-9a-f]+)"'
          url: "https://sepolia.explorer.zksync.io/tx/${__value.raw}"
          urlDisplayLabel: "zkSync Explorer"
